### ISSUE TITLE
Issue adding custom component to Home assistant

### ISSUE THREAD

**Issue by stefantrav** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#10]
i am using HA 0.89.1

Log Details (ERROR)
Thu Mar 14 2019 14:13:35 GMT+0100 (Midden-Europese standaardtijd)
Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/auth.py", line 98, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/view.py", line 112, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/config/core.py", line 21, in post
    errors = await async_check_ha_config_file(request.app['hass'])
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/config.py", line 779, in async_check_ha_config_file
    check_ha_config_file, hass)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/scripts/check_config.py", line 371, in check_ha_config_file
    platform = loader.get_platform(hass, domain, p_name)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 97, in get_platform
    base_paths)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/afvalwijzer/sensor.py", line 73
    url = (f"https://json.{url}/?method=postcodecheck&postcode={postcode}&street=&huisnummer={huisnummer}&toevoeging={toevoeging}&platform=phone&langs=nl&")
                                                                                                                                                          ^
SyntaxError: invalid syntax

**Comment by xirixiz** [comment]
Hi, do you see a page full with text when you use the following url? Please replace {postcode} and {huisnummer} with the values which apply to your location:

```https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode={postcode}&street=&huisnummer={huisnummer}&toevoeging=&platform=phone&langs=nl&```

**Comment by stefantrav** [comment]
yes

**Comment by xirixiz** [comment]
Ah, I think your using python2 instead of python3....

**Comment by stefantrav** [comment]
arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.5.3
timezone | Europe/Amsterdam
version | 0.89.1
virtualenv | true

**Comment by xirixiz** [comment]
https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/issues/8

You have to use a newer version of python:
