### ISSUE TITLE
Sensors.trash fails

### ISSUE THREAD

**Issue by remyderuysscher** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#15]
HA 0.93.2 for each sensor

> 2019-05-26 08:07:34 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_pmd_date fails
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 375, in async_device_update
>     await self.async_update()
>   File "/usr/src/app/homeassistant/components/template/sensor.py", line 191, in async_update
>     self._state = self._template.async_render()
>   File "/usr/src/app/homeassistant/helpers/template.py", line 191, in async_render
>     return self._compiled.render(kwargs).strip()
>   File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "<template>", line 1, in top-level template code
>   File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 438, in call
>     return __context.call(__obj, *args, **kwargs)
>   File "/usr/src/app/homeassistant/helpers/template.py", line 699, in strptime
>     return datetime.strptime(string, fmt)
> TypeError: strptime() argument 1 must be str, not Undefined
> 2019-05-26 08:07:34 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_papier_date fails
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 375, in async_device_update
>     await self.async_update()
>   File "/usr/src/app/homeassistant/components/template/sensor.py", line 191, in async_update
>     self._state = self._template.async_render()
>   File "/usr/src/app/homeassistant/helpers/template.py", line 191, in async_render
>     return self._compiled.render(kwargs).strip()
>   File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "<template>", line 1, in top-level template code
>   File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 438, in call
>     return __context.call(__obj, *args, **kwargs)
>   File "/usr/src/app/homeassistant/helpers/template.py", line 699, in strptime
>     return datetime.strptime(string, fmt)
> TypeError: strptime() argument 1 must be str, not Undefined

**Comment by remyderuysscher** [comment]
Can be closed
