### ISSUE TITLE
sensor.trash_day_after_tomorrow error. shows up 12 times and going up.

### ISSUE THREAD

**Issue by MrUserY** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#67]
Hi!

I've updated to the new version 4.3.0 with HACS. I'm getting an error wich I haven't got before. The error is only about sensor.trash_day_after_tomorrow.

Here is the error:

2020-06-16 20:52:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

2020-06-16 20:53:14 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_day_after_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalwijzer/sensor.py", line 142, in async_update
    if item['value'] != 'None':
KeyError: 'value'
2020-06-16 20:53:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_day_after_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalwijzer/sensor.py", line 142, in async_update
    if item['value'] != 'None':
KeyError: 'value'

2020-06-16 20:54:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_day_after_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalwijzer/sensor.py", line 142, in async_update
    if item['value'] != 'None':
KeyError: 'value'
2020-06-16 20:54:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.trash_day_after_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/afvalwijzer/sensor.py", line 142, in async_update
    if item['value'] != 'None':
KeyError: 'value'

## Environment

Frontend version: 20200603.3 - latest
arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.126-v7l
python_version | 3.7.7
supervisor | 227
timezone | Europe/Amsterdam
version | 0.111.3
virtualenv | false

**Comment by xirixiz** [comment]
I just noticed the same indeed, I`ll look into it and fix it asap

**Comment by MrUserY** [comment]
Thanks!

Did not made it an “official” integration yet? :) People where asking about where to find it, I sayed yeah you need to install hacs... :)

**Comment by xirixiz** [comment]
Done, release 4.3.1 fixed the issue. 

I'd like to make it official, but as a lonewolf I don't have enough time to integrate it...

**Comment by MrUserY** [comment]
Ah.
Oke. Seems whe're fine again with 4.3.1
I thank u and close this issue :-)
