### ISSUE TITLE
local variable 'jsonResponse' referenced before assignment

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#71]
Just letting you know, after yesterdays burn-down an quick fix (thanks for that), we now see a new error:

```
2020-09-11 09:29:27 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 63, in async_setup_platform
    afvaldienst = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 43, in __init__
    self._jsonData = self.__get_data_json()
  File "/usr/local/lib/python3.8/site-packages/Afvaldienst/Afvaldienst.py", line 55, in __get_data_json
    jsonData = (jsonResponse['data']['ophaaldagen']['data'] + jsonResponse['data']['ophaaldagenNext']['data'])
UnboundLocalError: local variable 'jsonResponse' referenced before assignment
```

not sure if this is still a Afvalwijzer server issue or an integration error, so posting it here for reference.

**Comment by xirixiz** [comment]
True, because there is no data being received, jsonResponse has no value, hence the error. I`m creating proper error handling atm.
